name: Android CI

on:
  push:
    tags:
      - v*.*

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      signedReleaseFile: ${{ steps.sign_app.outputs.signedReleaseFile }}
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Decode Keystore
      env:
        ENCODED_STRING: ${{ secrets.SIGNING_KEY }}
      run: |
        echo $ENCODED_STRING > keystore-b64.txt
        base64 -d keystore-b64.txt > app/keystore.jks

    - name: Build with Gradle
      env:
        SIGNING_KEY_ALIAS: ${{ secrets.ALIAS }}
        SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        SIGNING_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
      run: ./gradlew assembleRelease

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-artifacts
        path: |
          app/build/outputs/apk/release/*.apk

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v4
      with:
        name: release-artifacts

    - name: Create Release
      uses: ncipollo/release-action@v1.14.0
      with:
        draft: true
        tag: ${{ github.ref }}
        name: Androminion ${{ github.ref }}
        body: Todo
        artifactErrorsFailBuild: true
        artifacts: Androminion*.apk