name: Android CI

on:
  push:
    branches: ["master", "Issues"]
    tags:
      - v*.*.*
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      signedReleaseFile: ${{ steps.sign_app.outputs.signedReleaseFile }}
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleRelease

    - name: Sign app APK
      uses: r0adkll/sign-android-release@v1
      id: sign_app
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        path: ${{steps.sign_app.outputs.signedReleaseFile}}

    - name: Cache
      uses: actions/cache@v3.0.8
      with:
        path: ${{steps.sign_app.outputs.signedReleaseFile}}
        key: signedReleaseFile

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: Release &#x20;
        draft: true
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Cache
      uses: actions/cache@v3.0.8
      with:
        path: ${{needs.build.outputs.signedReleaseFile}}
        key: signedReleaseFile

    - name: Upload APK
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ needs.build.outputs.signedReleaseFile }}
        asset_name: Androminion-${{ github.ref_name }}.apk
        asset_content_type: application/zip
      env:
        GITHUB_TOKEN: ${{ github.token }}
